name: build
on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Cache gradle
              uses: actions/cache@v2
              with:
                  path: |
                      - /root/.gradle/caches/
                      - /root/.gradle/wrapper/
                  key: ${{ runner.os }}-${{ hashFiles('build.gradle') }}
          #- name: Build with Docker
          #run: HOME=/root && ./docker-build.sh
            # Deploy forge
            - name: Variables
              id: variables
              uses: actions/github-script@0.9.0
              with:
                script: |
                    const refName = context.ref.split('/').pop()
                    const isRelease = context.event_name != 'pull_request' && (
                        refName.startsWith('luckyblocktest-')
                        || refName.startsWith('template-addon-')
                    )

                    console.log(refName)
                    console.log(isRelease)
                    console.log(context.event_name)
                    core.setOutput('refName', refName)
                    core.setOutput('isRelease', isRelease)
            - name: Deploy
              if: ${{ steps.variables.outputs.isRelease }}
              uses: appleboy/scp-action@master
              with:
                  host: luckyblockmod.com
                  username: root
                  key: ${{ secrets.LUCKYBLOCKMOD_COM_KEY }}
                  source: ${{ steps.variables.outputs.refName }}
                  target: "~/luckyblock-dist"
